"use client";
import {useEffect,useState} from "react";
import {Leaf,Bot,Truck,ShieldCheck,Sparkles,ArrowRight} from "lucide-react";
import {getDemo,getHealth,getAnalytics,startNegotiation,runNegotiation,approve} from "../lib/api";
export default function Home(){
 const [demo,setDemo]=useState<any>(null),[run,setRun]=useState<any>(null),[stats,setStats]=useState<any>(null);
 const [cloud,setCloud]=useState("CONNECTING"),[busy,setBusy]=useState(false),[err,setErr]=useState("");
 async function refresh(){try{await getHealth();setCloud("ONLINE");setDemo(await getDemo());setStats(await getAnalytics());setErr("")}catch{setCloud("WAKING");setErr("Cloud backend may be waking. Retry shortly.")}}
 useEffect(()=>{refresh()},[]);
 async function launch(){setBusy(true);try{const s=await startNegotiation();setRun(await runNegotiation(s.id))}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 async function accept(){if(!run)return;setBusy(true);try{setRun(await approve(run.id));setStats(await getAnalytics())}finally{setBusy(false)}}
 const s=demo?.seller,b=demo?.buyer;
 return <main className="min-h-screen"><header className="border-b bg-white"><div className="max-w-7xl mx-auto px-6 py-4 flex justify-between"><div className="flex gap-3 items-center"><div className="h-10 w-10 rounded-2xl bg-emerald-600 text-white grid place-items-center"><Leaf/></div><div><b>ReFresh AI</b><div className="text-xs text-slate-500">Autonomous B2B Perishable Exchange</div></div></div><span className={`badge ${cloud==="ONLINE"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>● {cloud}</span></div></header>
 <section className="max-w-7xl mx-auto p-6 py-12"><div className="grid lg:grid-cols-2 gap-8"><div><span className="badge bg-slate-900 text-white">FINAL HACKATHON 2026</span><h1 className="text-5xl font-black mt-5">AI agents rescue value before perishables lose it.</h1><p className="text-lg text-slate-600 mt-5">Agents negotiate independently. Python enforces hard limits. Supabase persists the transaction trail.</p><button disabled={busy||cloud!=="ONLINE"} onClick={launch} className="mt-7 bg-emerald-600 text-white rounded-xl px-5 py-3 font-bold flex gap-2"><Sparkles/> {busy?"Agents working...":"Run autonomous demo"} <ArrowRight/></button>{err&&<div className="mt-4 p-4 bg-amber-50 rounded-xl">{err} <button onClick={refresh} className="underline font-bold">Retry</button></div>}</div>
 <div className="card p-6"><div className="text-xs font-bold text-slate-500">AT-RISK INVENTORY</div><h2 className="text-3xl font-black mt-2">{s?.product||"Strawberries"}</h2><p className="text-slate-500">{s?.quantity_kg||50} kg • {s?.remaining_hours||48}h remaining</p><div className="grid grid-cols-2 gap-3 mt-6"><M l="Normal price" v={`Rs. ${s?.normal_price||900}/kg`}/><M l="Seller floor" v={`Rs. ${s?.min_price||550}/kg`}/><M l="Buyer ceiling" v={`Rs. ${b?.max_price||620}/kg`}/><M l="Match score" v={`${demo?.match?.score||100}%`}/></div></div></div>
 <div className="grid md:grid-cols-4 gap-4 mt-8"><M l="Food rescued" v={`${stats?.food_rescued_kg||0} kg`}/><M l="Recovered revenue" v={`Rs. ${stats?.seller_revenue_recovered||0}`}/><M l="Buyer savings" v={`Rs. ${stats?.buyer_savings||0}`}/><M l="Completed deals" v={`${stats?.completed_deals||0}`}/></div>
 <div className="grid md:grid-cols-4 gap-4 mt-8">{[[Bot,"Matching"],[Sparkles,"Negotiation"],[Truck,"Logistics"],[ShieldCheck,"Risk"]].map(([I,t]:any)=><div className="card p-5" key={t}><I className="text-emerald-600"/><b className="block mt-4">{t}</b></div>)}</div>
 {run&&<div className="card p-6 mt-8"><div className="flex justify-between"><div><small>AUTONOMOUS RUN #{run.id}</small><h2 className="text-2xl font-black">Negotiation Room</h2></div><span className="badge bg-blue-50 text-blue-700">{run.status}</span></div><div className="space-y-3 mt-5">{run.offers?.map((o:any,i:number)=><div className="border rounded-xl p-4 flex justify-between" key={i}><div><b>{o.actor.toUpperCase()} AGENT</b><p className="text-slate-500">{o.rationale}</p></div><div className="text-right"><b className="text-xl">Rs. {o.price_per_kg}/kg</b><small className="block">{o.decision.toUpperCase()}</small></div></div>)}</div>{run.status==="AWAITING_APPROVAL"&&<button onClick={accept} className="mt-5 bg-slate-900 text-white px-5 py-3 rounded-xl font-bold">Approve transaction</button>}{run.status==="COMPLETED"&&<div className="mt-5 bg-emerald-50 text-emerald-800 p-5 rounded-xl"><b>Transaction completed</b><div>{run.agreed_quantity} kg rescued at Rs. {run.agreed_price}/kg.</div></div>}</div>}
 </section></main>
}
function M({l,v}:{l:string,v:string}){return <div className="card p-4"><div className="text-xs text-slate-500">{l}</div><div className="font-black mt-1">{v}</div></div>}
